apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/linusyong/helm-charts
    targetRevision: v0.0.3
    path: metrics-server/v0.6.3
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc